### ISSUE TITLE
The status of event_set API (Use it in uct and ucs/async/thread)

### ISSUE THREAD

**Issue by hiroyuki-sato** [openucx/ucx#3682]
I'm creating a new `event_set` API for waiting event.
This is an umbrella API for `epoll` and `kqueue`.
It uses for porting OpenUCX to macOS (and another xBSD system like FreeBSD)
I'm modifying that `uct/tcp` and `ucs/async/thread.c` use event_set API.

This issue summaries that status.

- [x] extend event_set API for using in UCT layer. (#3683: merged) (Refactor #3746)
- [x] ucs/async/tread.c use event_set API. (#3610 force pushed)
- [x] uct/tcp use event_set API (#3698)
- [x] ucp/worker use event_set API (#3881, #3815) (Will revise after #3610 merge)

This modification discussed on #3652. Refactored by #3746

#3819 also relates to this issue.

**Comment by hiroyuki-sato** [comment]
All works completed. Thank you @dmitrygx!

**Comment by dmitrygx** [comment]
> All works completed. Thank you @dmitrygx!

@hiroyuki-sato Thank you too!
